# -*- coding: utf-8 -*-
"""Project001.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1feug42LST7wkWzjBrXent-fT6ih_ZVlH
"""

"""
Stage: Develeopment - 01
@author: Ayşenur Hanlı, 120202073
@author: Cem Cereb, 119202062
"""

import requests
from bs4 import BeautifulSoup

source = requests.get("https://www.imdb.com/chart/top/")

soup = BeautifulSoup(source.text,'html.parser')

movies = soup.find('tbody', class_="lister-list").find_all('tr')

for movie in movies:

  name = movie.find('td', class_="titleColumn").a.text

  rank = movie.find('td', class_="titleColumn").get_text(strip=True).split('.')[0]

  year = movie.find('td', class_="titleColumn").span.text.strip('()')

  rating = movie.find('td', class_="ratingColumn imdbRating").strong.text

  print(rank, name, year, rating)